version: 2

models:
  - name: stg_cc_parcel
    columns:
      ### PK ###
      - name: parcel_id
        tests:
          - unique
  - name: stg_cc_parcel_product
    columns:
      ### PK ###
      - name: "(parcel_id|| '-' ||model_name)"
        tests:
          - unique
          - not_null
              
